### PR TITLE
Added File Icons (Hidden By Default)

### PR DESCRIPTION
**Pull request by orizens**
file icons can be toggled on by using:  
```itg_show_file_icons: true```  
in sublime's settings.

### CODE REVIEW

**Comment by itsthatguy** [comment]
Wow, that was fast! Two things:

- Submit your PR against the `development` branch
- The changes should not be made directly in the theme files, rather in `src/itg.flat.mustache` & `src/colors.js`

Please read the [contributors' guide](CONTRIBUTING.md)

**Comment by orizens** [comment]
@itsthatguy ,
after gulp compile, all icons paths are escaped as: 
```Theme - itg.flat&#x2F;assets&#x2F;group-closed.png```

**Comment by itsthatguy** [comment]
@orizens that should be fixed on both development, and master

**Comment by orizens** [comment]
what do you mean?
do i need to the changes on both branches?

**Comment by itsthatguy** [comment]
Pull master into your branch

**Comment by orizens** [comment]
i did that.
anything missing?

**Pull request closed without merging**
