### PR TITLE
added icon files definition for the sidebar

### PR DESCRIPTION
**Pull request by orizens**
to show the file icons, this setting has to be true:  
```itg_show_file_icons: true```  

screen shot 2015-04-28 at 12 41 30 pm

### CODE REVIEW

**Comment by itsthatguy** [comment]
the folder icons look narrower with this, is that intentional?

**Comment by orizens** [comment]
hi.
in the first version, i had to tweak the folder icons to be exactly aligned with the file icons.
now it's broken and i'm trying to figure out why.

**Comment by Horray** [comment]
How would I use this?

**Comment by orizens** [comment]
this pull request is outdated and deprecated.
thanks.

**Pull request closed without merging**
