### PR TITLE
Added File Icons (Hidden By Default)

### PR DESCRIPTION
**Pull request by orizens**
add icons to the base mustache file.

### CODE REVIEW

**Comment by itsthatguy** [comment]
```shell
> theme-itg-flat@0.2.1 test /Users/itg/git/open-source/theme-itg-flat
> mocha



  Compile
    should generate valid JSON

      1) itg.flat.dark.aqua.sublime-theme

      2) itg.flat.dark.blue.sublime-theme

      3) itg.flat.dark.green.sublime-theme

      4) itg.flat.dark.orange.sublime-theme

      5) itg.flat.dark.sublime-theme

      6) itg.flat.dark.yellow.sublime-theme

      7) itg.flat.light.sublime-theme

  src
    merges base data as expected

      ✓ dark

      8) light


  1 passing (125ms)
  8 failing

  1) Compile should generate valid JSON itg.flat.dark.aqua.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.aqua.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.aqua.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  2) Compile should generate valid JSON itg.flat.dark.blue.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.blue.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.blue.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  3) Compile should generate valid JSON itg.flat.dark.green.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.green.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.green.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  4) Compile should generate valid JSON itg.flat.dark.orange.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.orange.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.orange.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  5) Compile should generate valid JSON itg.flat.dark.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  6) Compile should generate valid JSON itg.flat.dark.yellow.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.dark.yellow.sublime-theme: Unexpected token /
  SyntaxError: test/tmp/itg.flat.dark.yellow.sublime-theme: Unexpected token /
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  7) Compile should generate valid JSON itg.flat.light.sublime-theme:
     /Users/itg/git/open-source/theme-itg-flat/test/tmp/itg.flat.light.sublime-theme: Unexpected token ,
  SyntaxError: test/tmp/itg.flat.light.sublime-theme: Unexpected token ,
      at Object.parse (native)
      at Context.<anonymous> (test/index.js:25:9)

  8) src merges base data as expected light:
     Cannot find module '/Users/itg/git/open-source/theme-itg-flat/test/templates/light.js'
  Error: Cannot find module 'test/templates/light.js'
      at compareMerge (test/index.js:37:18)
      at Context.<anonymous> (test/index.js:52:18)


```

**Comment by itsthatguy** [comment]
please merge master into your branch, and resolve the test failures

**Comment by itsthatguy** [comment]
@orizens I take it back. I'm working through a bunch of issues right now on the new dev environment.

Merging, and resolving the tests now won't be of much help.

What is your timezone? Perhaps we could find a time to sync up, and come up with a plan.

**Comment by orizens** [comment]
hi.
i'm at gmt +3.

**Comment by itsthatguy** [comment]
Development branch has fixed tests... when you add your code you will need to update the files in `test/templates/`

**Comment by itsthatguy** [comment]
@orizens, everything is merged into master. I'll be hanging out in the gitter room all day if you want to chat about strategy

**Comment by itsthatguy** [comment]
I've tried to work through all of these changes. This PR is just simply too big to merge.

Please resubmit with minimal changes.

**Pull request closed without merging**
