### PR TITLE
adding file icons form DC theme

### PR DESCRIPTION
**Pull request by orizens**
Also, added 2 new settings to allow:
1. hiding tree folders
2. hiding file icons in tree  
Example:  
screen shot 2015-03-09 at 9 28 44 am

### CODE REVIEW

**Comment by baaboum** [comment]
Hello, thanks to work for add icons file on sidebar :) .
 if it's possible, how can i see your work on sublimetext 3 ?

**Comment by orizens** [comment]
hi @baaboum 
thanks.
what do you mean by "see your work on sublimetext 3"?

**Comment by itsthatguy** [comment]
This is cool. The icons don't fit the the me, however. I'd love to see a collection of white icons that fit the theme, and can be colored programmatically! Great work!

**Comment by venetianthief** [comment]
@itsthatguy I am not familiar with coding themes for Sublime. Is programmatically color coding the sidebar icons possible?

**Comment by itsthatguy** [comment]
@venetianthief I would think so. You could try using "layer0.tint": [255, 255, 255, 200] on the element that has the icon. icons are supposed to set the layer0.texture

**Comment by jchannon** [comment]
I'd like icons. I'm trying to get this to work but failing miserably https://github.com/mrmartineau/SetiUI-Icons-Sublime

**Comment by jchannon** [comment]
@orizens I cloned your repo and all looks good apart from the close icon on the active tab see below, it has a stripy effect as if it can't find the image

screen shot 2015-04-01 at 15 00 51

**Comment by itsthatguy** [comment]
@orizens can you resubmit using the new development environment and:
- file icons setting should default to hidden
- update readme to explain how to enable the file icons

I'd love to get this in, but merging now will break master... And not persist through future changes

**Comment by orizens** [comment]
@itsthatguy 
how do i pull the latest changed from your repo?

**Comment by jchannon** [comment]
in your local git repo do 
```
git remote add upstream https://github.com/itsthatguy/theme-itg-flat.git
git checkout master
git pull upstream master
git checkout -b myiconbranch
```

make your changes

`git push origin myiconbranch` -- this assumes origin is your fork of this repo

Open a PR :smile:

**Comment by orizens** [comment]
@jchannon thanks.  
did it :)

**Comment by jchannon** [comment]
no probs :)

**Comment by EmmanuelBeziat** [comment]
Hi @orizens 
I did try to use your version, but i'm facing this little problem here : 



What's the matter ? I've just put the folder of your fork in my Package files, renamed it correctly, used it and... There.

Thanks !

**Comment by orizens** [comment]
hi @EmmanuelBeziat .
I stopped maintaining it.
It doesn't work for me either.

**Comment by itsthatguy** [comment]
I believe there was an update to icons in ST3 that needs to be addressed

**Pull request closed without merging**
