### PR TITLE
italic the label text in tab, when the file is transient.

### PR DESCRIPTION
**Pull request by wanyaxing**

### CODE REVIEW

**Comment by itsthatguy** [comment]
Could you provide a description for this PR?

**Comment by wanyaxing** [comment]
1. Single-click file in project in sidebar, the file will be open as transient view. If you single-click another file, the last transient file will be replaced.

2.vDouble-clicked file will always leave in the window, until you close it.

For the different of these two status, in this PR, the tab font of transient file is italic.

qq20150523-2 2x

**Comment by itsthatguy** [comment]
This is sweet, can you make the changes via the [contributing instructions](https://github.com/itsthatguy/theme-itg-flat/blob/master/CONTRIBUTING.md)?

**Comment by itsthatguy** [comment]
thanks, and nice work! :+1:

**Comment by itsthatguy** [comment]
@wanyaxing Whoops. Can you please update the tests and make sure they pass. Then submit a new PR?

**Comment by itsthatguy** [comment]
I've updated Travis to test pull requests. This was my bad. Apologies.

**Pull request merged**
